### ISSUE TITLE
atob/btoa

### ISSUE THREAD

**Issue by keyle** [Aaronduino/serverless-chat#1]
Hi, just curious, is there any reason why you implemented your own Base64 function? 

https://github.com/aaronduino/serverless-chat/blob/2da01cf7746bed7b3d39cd3917b9e8b7da2a12e1/main.js#L9

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa

**Comment by aaronjanse** [comment]
Haha that's funny.

I guess I didn't know the builtin atob/btoa existed.

**Comment by aaronjanse** [comment]
The only problem is that the builtin functions cannot encode integers without converting them to strings.
That ends up making the encoded values really long, which is a problem when that number needs to be communicated by humans.

Any suggestions for a work-around?

**Comment by keyle** [comment]
hmm, no suggestion no.
